version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "< 11, >= 10.a"
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
    - 4.2.16
  - dependency-name: i18next
    versions:
    - 19.8.8
    - 19.8.9
    - 19.9.0
    - 19.9.1
    - 19.9.2
    - 20.0.0
    - 20.1.0
    - 20.2.1
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: jsdom
    versions:
    - 16.5.1
    - 16.5.2
  - dependency-name: "@types/express"
    versions:
    - 4.17.11
  - dependency-name: mime
    versions:
    - 2.4.6
    - 2.5.2
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: applicationinsights
    versions:
    - 1.8.10
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: govuk-frontend
    versions:
    - 3.11.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
  - dependency-name: "@hmcts/nodejs-healthcheck"
    versions:
    - 1.7.0
  - dependency-name: webdriverio
    versions:
    - 6.10.5
    - 7.0.2
  - dependency-name: typescript
    versions:
    - 3.9.8
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
  - dependency-name: uuid
    versions:
    - 8.3.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@types/nunjucks"
    versions:
    - 3.1.4
  - dependency-name: "@taoqf/javascript-state-machine"
    versions:
    - 3.1.6
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: "@types/config"
    versions:
    - 0.0.38
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
  - dependency-name: "@types/cookies"
    versions:
    - 0.7.6
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
  - dependency-name: config
    versions:
    - 3.3.3
