postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE cmc WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "claimstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  persistence:
    enabled: false

nodejs:
  image: ${IMAGE_NAME}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  ingressHost: ${SERVICE_FQDN}
  readinessDelay: 130  # claim-store will start much slower
  livenessDelay: 130  # claim-store will start much slower
  memoryRequests: 512Mi
  cpuRequests: 1000m
  memoryLimits: 1024Mi
  cpuLimits: 2500m
  devmemoryRequests: 512Mi
  devcpuRequests: 1000m
  devmemoryLimits: 1024Mi
  devcpuLimits: 2500m
  autoscaling:        # Default is false
    enabled: true
    maxReplicas: 5    # Required setting
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  environment:
    REFORM_TEAM: cmc
    REFORM_SERVICE_NAME: citizen-frontend
    LOG_LEVEL: DEBUG
    HTTP_TIMEOUT: 60000
    FEATURE_TOGGLES_API_URL: http://${SERVICE_NAME}-ftr-tgl
    CLAIM_STORE_URL: http://${SERVICE_NAME}-claim-store
    PAY_RETURN_URL: https://${SERVICE_FQDN}

    # config to make non prod testing easier
    FEATURE_TESTING_SUPPORT: true
    FEATURE_RETURN_ERROR_TO_USER: true
    # features
    FEATURE_FINE_PRINT: true
    FEATURE_NEW_DASHBOARD_STATUS: false
    FEATURE_WEB_CHAT: true
    PCQ_URL: http://localhost:4000

# sub-charts configuration

idam-pr:
  enabled: true
  redirect_uris:
    Money Claims - Citizen:
      - https://${SERVICE_FQDN}/receiver
  fr-am:
    image: hmctsprivate.azurecr.io/idam/idam-fr-am:latest
    releaseNameOverride: cmc-pr-fr-am

  fr-idm:
    image: hmctsprivate.azurecr.io/idam/idam-fr-idm:latest
    releaseNameOverride: cmc-pr-fr-idm
  idam-api:
    image: hmctspublic.azurecr.io/idam/api:stable
    releaseNameOverride: cmc-pr-idm-api
    ingressHost: idam-api-${SERVICE_FQDN}
    keyVaults:
      cmc:
        resourceGroup: cmc
        secrets:
          - notify-api-key
          - idam-spi-forgerock-idm-password
          - idam-spi-forgerock-idm-pin-defaultpassword
          - spring-datasource-password
          - idam-spi-forgerock-am-password
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - CACHING_ENABLED=false
      - SPRING_DATA_ELASTICSEARCH_PROPERTIES_PATH_HOME=/tmp/es
      - TESTING_SUPPORT_ENABLED=true
      - IDAMHEALTHCHECK_AM_ENABLED=false
      - IDAMHEALTHCHECK_IDM_ENABLED=false
      - STRATEGIC_ADMIN_URL=http://cmc-pr-idam-web-admin
      - STRATEGIC_WEBPUBLIC_URL=http://cmc-pr-idam-web-public
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${SERVICE_NAME}-postgresql/openidm?currentSchema=fridam
      - SPRING_DATASOURCE_USERNAME=openidm
      - SECURITY_OAUTH2_CLIENT_CLIENTSECRET=password #fake password
      - SECURITY_OAUTH2_CLIENT_PRE_ESTABLISHED_REDIRECT_URI=http://cmc-pr-idam-web-public/login
      - SECURITY_OAUTH2_CLIENT_REGISTERED_REDIRECT_URI=http://cmc-pr-idam-web-public/login
      - IDAM_SPI_FORGEROCK_AM_ROOT=http://cmc-pr-fr-am/openam
      - IDAM_SPI_FORGEROCK_AM_TOPLEVELHOST=fr-am
      - IDAM_SPI_FORGEROCK_AM_USERNAME=amadmin
      - IDAM_SPI_FORGEROCK_AM_JWKSURIFOROAUTH2CLIENTS=http://cmc-pr-fr-am/openam/oauth2/hmcts/connect/jwk_uri
      - IDAM_SPI_FORGEROCK_IDM_ROOT=http://cmc-pr-fr-idm/openidm
      - IDAM_SPI_FORGEROCK_IDM_USERNAME=openidm-admin #fake user
      - APPINSIGHTS_INSTRUMENTATIONKEY=fake-key

  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:stable
    releaseNameOverride: cmc-pr-idm-web-public
    ingressHost: idam-web-public-${SERVICE_FQDN}
    environment:
      - STRATEGIC_SERVICE_URL=http://cmc-pr-idam-api

  idam-web-admin:
    image: hmctspublic.azurecr.io/idam/web-admin:stable
    releaseNameOverride: cmc-pr-idm-web-admin
    ingressHost: idam-web-admin-${SERVICE_FQDN}
    environment:
      - STRATEGIC_SERVICE_URL=http://cmc-pr-idam-api
      - STRATEGIC_PUBLIC_URL=http://cmc-pr-idam-web-public

  idam-importer:
    build:
      context: docker/idam-importer  # local
    keyVaults:
      cmc:
        resourceGroup: cmc
        secrets:
          - idam-admin-password
    environment:
      - IDAM_API_URL=http://cmc-pr-idam-api
      - IDAM_ADMIN_USER=idamowner%40hmcts.net #fake
      - WAIT_HOSTS=cmc-pr-idam-api
      - WAIT_HOSTS_TIMEOUT=900

  service-auth-provider-api:
    image: hmctspublic.azurecr.io/rpe/service-auth-provider
    releaseNameOverride: cmc-pr-service-auth-provider-api
    environment:
      - SERVER_PORT=8080
      - JWT_KEY=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA== #fake jwt key for pr testing
      - MICROSERVICEKEYS_CMC=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CMC_CLAIM_SUBMIT_API=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CMC_LEGAL_FRONTEND=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CMC_CLAIM_STORE=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_EM_GW=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CCD_DATA=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CCD_DEFINITION=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_CCD_GATEWAY=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_DG_DOCASSEMBLY_API=AAAAAAAAAAAAAAAA
      - MICROSERVICEKEYS_XUI_WEBAPP=XUIXUIXUIXUIXUIX
      - TESTING_SUPPORT_ENABLED=true


cmc-claim-store:
  enabled: true
  java:
    image: hmctspublic.azurecr.io/cmc/claim-store:latest
    releaseNameOverride: ${SERVICE_NAME}-claim-store
    ingressHost: claim-store-${SERVICE_FQDN}
    imagePullPolicy: Always
    readinessDelay: 250  # ccd-stack will start much slower
    livenessDelay:  250  # ccd-stack will start much slower
    keyVaults:
      cmc:
        resourceGroup: cmc
        secrets:
          - AppInsightsInstrumentationKey
          - citizen-oauth-client-secret
          - claim-store-s2s-secret
          - anonymous-caseworker-username
          - anonymous-caseworker-password
          - system-update-username
          - system-update-password
          - notify-api-key
          - milo-recipient
          - staff-email
          - live-support-email
          - rpa-email-sealed-claim
          - rpa-email-more-time-requested
          - rpa-email-response
          - rpa-email-ccj
          - rpa-email-paid-in-full
          - launchDarkly-sdk-key
          - sendgrid-api-key
          - staff-email-legal-rep
    environment:
      LOG_LEVEL: DEBUG
      DOC_ASSEMBLY_URL: http://dg-docassembly-aat.service.core-compute-aat.internal
      FRONTEND_BASE_URL: https://${SERVICE_FQDN}
      RESPOND_TO_CLAIM_URL: https://${SERVICE_FQDN}/first-contact/start
      CMC_DB_HOST: ${SERVICE_NAME}-postgresql
      CMC_DB_USERNAME: hmcts
      CMC_DB_PASSWORD: hmcts
      CMC_DB_CONNECTION_OPTIONS: ''
      CORE_CASE_DATA_API_URL: http://cmc-pr-ccd-data-store-api
      STAFF_NOTIFICATIONS_LEGAL_RECIPIENT: moneyclaims@justice.gov.uk
      RPA_NOTIFICATIONS_LEGALSEALEDCLAIMRECIPIENT: civilmoneyclaims+rpa-legal-claim-issued@gmail.com

ccd:
  enabled: true
  ccd:
    s2s:
      enabled: false
    postgresql:
      enabled: false
    adminWeb:
      enabled: true

  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}

  global:
    idamApiUrl: http://cmc-pr-idam-api
    idamWebUrl: http://cmc-pr-idam-web-public
    s2sUrl: http://cmc-pr-service-auth-provider-api
    ccdAdminWebIngress: ccd-admin-web-${SERVICE_FQDN}
    ccdDefinitionStoreUrl: http://cmc-pr-ccd-definition-store
    ccdUserProfileUrl: http://cmc-pr-ccd-user-profile-api
    postgresUsername: hmcts
    postgresPassword: hmcts
    devMode: true

  ccd-admin-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/admin-web:latest
      ingressHost: ccd-admin-web-${SERVICE_FQDN}
      releaseNameOverride: cmc-pr-ccd-admin-web
      keyVaults: []
      environment:
        IDAM_OAUTH2_AW_CLIENT_SECRET: ${ADMIN_WEB_IDAM_SECRET}
    idam-pr:
      enabled: true

  ccd-user-profile-api:
    java:
      image: hmctspublic.azurecr.io/ccd/user-profile-api:latest
      releaseNameOverride: cmc-pr-ccd-user-profile-api
      keyVaults: []
      environment:
        USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,ccd_admin,cmc_claim_store

  ccd-definition-store-api:
    java:
      image: hmctspublic.azurecr.io/ccd/definition-store-api:latest
      releaseNameOverride: cmc-pr-ccd-definition-store-api
      ingressHost: ccd-definition-store-api-${SERVICE_FQDN}
      imagePullPolicy: Always
      keyVaults: []
      environment:
        DEFINITION_STORE_IDAM_KEY: ${DEFINITION_STORE_S2S_KEY}
        DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin,cmc_claim_store
        IDAM_USER_URL: http://cmc-pr-idam-web-public
        OIDC_ISSUER: http://cmc-pr-fr-am/openam/oauth2/hmcts

  ccd-data-store-api:
    java:
      image: hmctspublic.azurecr.io/ccd/data-store-api:latest
      releaseNameOverride: cmc-pr-ccd-data-store-api
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
      keyVaults: []
      environment:
        DATA_STORE_IDAM_KEY: ${DATA_STORE_S2S_KEY}
        IDAM_S2S_URL: http://cmc-pr-service-auth-provider-api
        IDAM_USER_URL: http://cmc-pr-idam-web-public
        OIDC_ISSUER: http://cmc-pr-fr-am/openam/oauth2/hmcts

  ccd-user-profile-importer:
    image: hmctspublic.azurecr.io/ccd/user-profile-importer:db2r9a
    releaseNameOverride: cmc-pr-ccd-user-profile-importer
    users:
      - civilmoneyclaims+ccd@gmail.com|CMC|MoneyClaimCase|open
      - civilmoneyclaims+judge@gmail.com|CMC|MoneyClaimCase|orderForJudgeReview
      - civilmoneyclaims+la@gmail.com|CMC|MoneyClaimCase|readyForDirections

  ccd-definition-importer:
    image: hmctspublic.azurecr.io/cmc/ccd-definition-importer:1.10.0
    releaseNameOverride: cmc-pr-ccd-definition-importer
    environment:
      CCD_DEF_CLAIM_STORE_BASE_URL: http://${SERVICE_NAME}-claim-store
    definitionFilename: cmc-ccd.xlsx
    userRoles:
      - citizen
      - caseworker-cmc
      - caseworker-cmc-solicitor
      - caseworker-cmc-systemupdate
      - letter-holder
      - caseworker-autotest1
      - caseworker-cmc-anonymouscitizen
      - caseworker-cmc-judge
      - caseworker-cmc-legaladvisor
      - caseworker-cmc-pcqextractor
      - payments
